### PR TITLE
Friendships v1: Create friendships using 3 column system.

### PR DESCRIPTION
**Pull request by franklinben23**
For this milestone of the project we managed to create a friendships system that allows you to have all the functions you need for sending friend requests, accepting and rejecting them, see your friends and other user's, and all the functionality of the base app.

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨

- Good work preparing the basic database and model structure for this project.

## However, there are some changes required 👀 🧰 🔨 🔧
- When I first log in and I have no friendships, I can still see all the posts from all the users. I'm supposed to only be able to see the posts by the users that have accepted my friendship requests. Please fix this.
- When I send a friend request to another user, the other user should see 2 buttons: one to accept, and another to reject the friend request. Currently, your app shows neither. Please fix this.
- I tried sending a friend request to another user and the other user only shows the same "INVITE TO FRIENDSHIP" button as all the other users. There is no change on the receiving user's side. As mentioned before: please fix this.
- Apply all the necessary changes on your models and database to fix these bugs.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Comment by franklinben23** [comment]
NOTE: To check on the friend requests and actually accept/reject them you will have to enter to your personal profile.

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Great job implementing the requested changes by the previous reviewer.

## To Improve
You have shown a great effort so far, however, your project is still missing a few requirements, kindly implement these and resubmit for review.

- [x] Posts timeline should include posts written by the logged-in user and their friends, right now I cannot see my own post, only those of my friends, please fix this ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

## Nice to have (Optional)
Note that these are optional suggestions, while they are nice to improve your project, you are not obliged to implement them.
- [x] I was unable to run `rspec` on your project, it output this error below when I try.
`cannot load such file -- rspec/core/formatters/progress_formatter (LoadError)`
- [x] In the `Users#index` and `User#show` view, it would be nice to display **accept** and **reject** friendship buttons for users who have sent me a friend request. Right now it still shows `invite to friendship` button, you would agree it doesn't make sense to be able to send a friend request to a user who has also sent me a friend request.

Happy coding, see you at the top.


> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Good work fixing some of the previously pointed out issues.
## However, there are some changes required 👀 🧰 🔨 🔧
- When I receive a friendship request, I have no method to accept it from my side. All I can see is the other user's profile with a message that tells me they sent me a request, but there is no button to accept it. Please fix this by adding a button to accept friendships.
image
- I can still see all the posts from every user. I created multiple test accounts and wrote a post from each of them without accepting any friendships (mainly because it's currently impossible), and I still can see all posts, even though none of them are my friends:
image
- Please fix these bugs.
### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by GzimAsani — APPROVED** [review]
# STATUS: Millstone Accepted :green_circle: :clap: 

### Good job @franklinben23 and @diamond-nicholas, thank you for making all the required changes asked from previous TSE-s. Your may merge now and continue with the next millstone
- [ OPTIONAL ] Add colors to the accept and reject button they will look better/more professional


# HAPPY CODING :computer: :desktop_computer:

**Pull request merged**
